import { Flight } from './flight.model';
export const DATA: Array<Flight> = [
  {
    idVoyage: 1,
    compagnieName: 'Air France',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 2,
    compagnieName: 'Air Corsica',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 3,
    compagnieName: 'Air Senegal',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 4,
    compagnieName: 'Air Caraibes',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 5,
    compagnieName: 'Aegean Airlines',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 6,
    compagnieName: 'ASL Airlines France',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 7,
    compagnieName: 'Austrian Airlines',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 8,
    compagnieName: 'Alitalia',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
  {
    idVoyage: 9,
    compagnieName: 'Ariana Afghan Airlines',
    modeVoyage: 'Allez simple',
    typeVol: 'direct',
    typeAvion: 'jet privé',
    provenance: 'France',
    destination: 'Senegal',
    dateDepart: new Date(),
    dateArrive: new Date(),
  },
];
